AWSTemplateFormatVersion: "2010-09-09"
Description: "Loaded Balanced Web servers"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.10.0/16 
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.10.10.0/24
      MapPublicIpOnLaunch: true
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.10.20.0/24
      MapPublicIpOnLaunch: true

  WebInstance1: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-b6bb47d4"
      KeyName: "automation"
      InstanceType: t2.nano
      SecurityGroups:
        - !Ref WebSecurityGroup
      BlockDeviceMappings:
        - 
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64:
          yum update -y
          rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
          yum install -y puppet

      Tags: 
        - 
          Key: Name
          Value: web1
        - 
          Key: CloudFormation
          Value: True
  
  WeSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VPC
      GroupName: any_ssh_http_https
      GroupDescription: Allow ssh http and https from anywhere
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
        
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
        
      - IpProtocol: tcp
        FromPort: 433
        ToPort: 443
        CidrIp: 0.0.0.0/0
        
      SecurityGroupEgress:
      - IpProtocol: "-1"
        CidrIp: 0.0.0.0/0


